#!/usr/bin/env bash
# Generate lib/build_info.dart with the exact app + native-engine revisions.
# Run before `flutter build` — called by build_macos.sh, build_linux.sh,
# release.yml, and deploy-web.yml.
set -euo pipefail

cd "$(dirname "$0")/.."

SHORT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
FULL=$(git rev-parse HEAD 2>/dev/null || echo "unknown")
if [[ -n "$(git status --porcelain --untracked-files=normal 2>/dev/null)" ]]; then
  SHORT="${SHORT}-dirty"
  FULL="${FULL}-dirty"
fi
TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

repo_version() {
  local repo="$1"
  local manifest="$2"
  if [[ ! -d "$repo/.git" || ! -f "$repo/$manifest" ]]; then
    printf 'unknown'
    return
  fi
  sed -n 's/^version:[[:space:]]*//p' "$repo/$manifest" | head -1
}

repo_revision() {
  local repo="$1"
  if [[ ! -d "$repo/.git" ]]; then
    printf 'unknown'
    return
  fi
  git -C "$repo" rev-parse HEAD 2>/dev/null || printf 'unknown'
}

CRISPASR_DIR="${CRISPASR_DIR:-../CrispASR}"
CRISPEMBED_DIR="${CRISPEMBED_DIR:-../CrispEmbed}"
GLINT_DIR="${GLINT_DIR:-../glint}"

CRISPASR_VERSION=$(repo_version "$CRISPASR_DIR" flutter/crispasr/pubspec.yaml)
CRISPASR_REVISION=$(repo_revision "$CRISPASR_DIR")
CRISPEMBED_VERSION=$(repo_version "$CRISPEMBED_DIR" flutter/crispembed/pubspec.yaml)
CRISPEMBED_REVISION=$(repo_revision "$CRISPEMBED_DIR")
GLINT_VERSION=$(repo_version "$GLINT_DIR" bindings/dart/pubspec.yaml)
GLINT_REVISION=$(repo_revision "$GLINT_DIR")

cat > lib/build_info.dart <<EOF
// AUTO-GENERATED by scripts/gen_build_info.sh — do not edit manually.
// Re-generated before every build via the build scripts and CI workflows.
// ignore_for_file: constant_identifier_names

const String kBuildGitHash = '$SHORT';
const String kBuildGitHashFull = '$FULL';
const String kBuildTimestamp = '$TS';
const String kCrispAsrVersion = '$CRISPASR_VERSION';
const String kCrispAsrRevision = '$CRISPASR_REVISION';
const String kCrispEmbedVersion = '$CRISPEMBED_VERSION';
const String kCrispEmbedRevision = '$CRISPEMBED_REVISION';
const String kGlintVersion = '$GLINT_VERSION';
const String kGlintRevision = '$GLINT_REVISION';
EOF

echo "gen_build_info: app=$SHORT crispasr=${CRISPASR_VERSION}@${CRISPASR_REVISION:0:7} crispembed=${CRISPEMBED_VERSION}@${CRISPEMBED_REVISION:0:7} glint=${GLINT_VERSION}@${GLINT_REVISION:0:7} ($TS)"
